import '@/styles/globals.css';
import { QueryProvider, SessionProvider } from './provider';

export const metadata = {
  title: 'Keylog',
  description: 'Generated by Next.js v15',
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="kr">
      <body>
        <QueryProvider>
          <SessionProvider>{children}</SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
