import '@/styles/globals.css';
import { Scaffold } from '@/shared/ui/layout';
import { getCustomSession } from '@/shared/lib/util';
import { QueryProvider, SessionProvider } from './provider';

export const metadata = {
  title: 'Keylog',
  description: 'Generated by Next.js v15',
};
export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getCustomSession();

  return (
    <html lang="kr">
      <body>
        <QueryProvider>
          <SessionProvider session={session}>
            <Scaffold>{children}</Scaffold>
          </SessionProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
